In [7]:
import numpy as np
import torch
import random

In [15]:
A=[]
for i in range(10):
    A.append(random.randint(1,100))
A

[1, 37, 34, 97, 10, 25, 79, 56, 91, 40]

In [16]:
a = torch.ones(3)

In [17]:
a

tensor([1., 1., 1.])

In [18]:
a[1]

tensor(1.)

In [19]:
a[0]

tensor(1.)

In [20]:
float(a[0])

1.0

In [21]:
a[2]=4
a

tensor([1., 1., 4.])

In [22]:
thistuple = ("apple", "banana", "cherry")
print(thistuple)

('apple', 'banana', 'cherry')


In [23]:
points = torch.zeros(6)
points[0]=4.0
points[1]=1.0
points[2]=5.0
points[3]=3.0
points[4]=2.0
points[5]=1

points


tensor([4., 1., 5., 3., 2., 1.])

In [24]:
x,y =float(points[0]),float(points[1])
x,y

(4.0, 1.0)

In [32]:
points = torch.tensor([[4,0],[5,3],[2,1]])
points

tensor([[4., 0.],
        [5., 3.],
        [2., 1.]])

In [35]:
points.shape

torch.Size([3, 2])

In [39]:
P = torch.ones(3,2)
P
P.shape

torch.Size([3, 2])

In [40]:
torch.__version__

'2.5.0+cpu'