In [48]:
import math;
import torch
a = torch.tensor(range(9))
a.size() ,a.storage_offset(),a.stride()
a

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [49]:
b= a.view(3,3)
b

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [50]:
a

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [51]:
id(a.untyped_storage)==id(b.untyped_storage) #checking if a,b share same storage

True

In [52]:
c= b[1:,1:]
c

tensor([[4, 5],
        [7, 8]])

In [53]:
c.size(),c.storage_offset(),c.stride()

(torch.Size([2, 2]), 4, (3, 1))

In [54]:
#cosine operation
a

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [55]:
torch.cos(a) #radian

tensor([ 1.0000,  0.5403, -0.4161, -0.9900, -0.6536,  0.2837,  0.9602,  0.7539,
        -0.1455])

In [56]:
torch.cos(a*math.pi/180) #degrees

tensor([1.0000, 0.9998, 0.9994, 0.9986, 0.9976, 0.9962, 0.9945, 0.9925, 0.9903])

In [57]:
#element wise
print(torch.cos(a[0]))

tensor(1.)
