In [1]:
import torch
import numpy as np
import h5py
# points_gpu = torch.tensor([],device='cuda') 
points = torch.ones(3,4,5)
pointN= points.numpy() #to numpy
pointNn = torch.tensor(pointN) # to tensor 
pointNn = torch.from_numpy(pointN)
#it is important to remember default datatype in torch is float32 , in numpy its 64 , so we need to convert to float32

pointNn


tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]])

In [ ]:
torch.save(pointNn,'OurPoints.t') #saving tensors.t file , .t files can be opened only with pytorch
#alternate method 
with open('./OurPoints.t','wb') as f :
    points = torch.save(points,f)


In [ ]:
pointsFromFile = torch.load('./OurPoints.t',weights_only=True) #reading from file
#alternate method 
with open('./OurPoints.t','rb') as f :
    points = torch.load(f,weights_only=True)
points

tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]])

In [11]:
#write using h5py
f = h5py.File('./OurPoints.hdf5','w') #this Ourpoints.hdf5 is created on memory
dset = f.create_dataset('coords',data=pointNn.numpy()) 
f.close()
dset

<Closed HDF5 dataset>

In [27]:
##read using h5py
f= h5py.File("./OurPoints.hdf5",'r')
dset = f['coords']
last_points = dset[-2:] # accessing last 2 elements
X = dset[:]
f.close()

In [28]:
last_points

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]], dtype=float32)

In [29]:
X

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]], dtype=float32)

In [ ]:
type(X) #return numpy array from tensor 

numpy.ndarray

In [31]:
XX = torch.from_numpy(X)
XX

tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]])