In [1]:
import numpy as np
import torch
import random

In [2]:
A=[]
for i in range(10):
    A.append(random.randint(1,100))
A

[81, 62, 78, 91, 86, 16, 45, 27, 82, 88]

In [3]:
a = torch.ones(3)

In [4]:
a

tensor([1., 1., 1.])

In [18]:
a[1]

tensor(1.)

In [19]:
a[0]

tensor(1.)

In [20]:
float(a[0])

1.0

In [21]:
a[2]=4
a

tensor([1., 1., 4.])

In [22]:
thistuple = ("apple", "banana", "cherry")
print(thistuple)

('apple', 'banana', 'cherry')


In [23]:
points = torch.zeros(6)
points[0]=4.0
points[1]=1.0
points[2]=5.0
points[3]=3.0
points[4]=2.0
points[5]=1

points


tensor([4., 1., 5., 3., 2., 1.])

In [24]:
x,y =float(points[0]),float(points[1])
x,y

(4.0, 1.0)

In [9]:
points = torch.tensor([[4,0],[5,3],[2,1]])
points[0][0]
for i in points :
    print(float(i[0]),float(i[1]))
print(points.size())

4.0 0.0
5.0 3.0
2.0 1.0
torch.Size([3, 2])


In [35]:
points.shape

torch.Size([3, 2])

In [39]:
P = torch.ones(3,2)
P
P.shape

torch.Size([3, 2])

In [40]:
torch.__version__

'2.5.0+cpu'

In [2]:
B= torch.tensor([1,2,3,4])
B

tensor([1, 2, 3, 4])

In [14]:
X = np.zeros(10)
X
Y=[0]*10
Y

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [15]:
some_list = list(range(10))
some_list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [18]:
some_list[:]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [19]:
some_list[1:4]

[1, 2, 3]

In [20]:
some_list[1:]

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [21]:
some_list[:4]

[0, 1, 2, 3]

In [23]:
some_list[:-1]

[0, 1, 2, 3, 4, 5, 6, 7, 8]

In [25]:
some_list[1:4:2]

[1, 3]

In [46]:
some_tensor = torch.tensor([[10,12],[10,12],[10,22],[10,12],[10,12],[10,22]])

In [47]:
some_tensor.shape

torch.Size([6, 2])

In [57]:
points = torch.tensor([[4,0],[5,3],[2,1]])
points

tensor([[4, 0],
        [5, 3],
        [2, 1]])

In [49]:
points[1:]

tensor([[5, 3],
        [2, 1]])

In [55]:
points[1:,0]

tensor([5, 2])

In [56]:
points[None]

tensor([[[4, 0],
         [5, 3],
         [2, 1]]])

In [ ]:
img_t = torch.randn(3,5,5) #generates tensor of 3x5x5
img_t

In [82]:
weights = torch.tensor([0.2126,0.7152,0.0722])
batch_t = torch.randn(2,3,5,5)
img_t.shape,batch_t.shape

(torch.Size([3, 5, 5]), torch.Size([2, 3, 5, 5]))

In [80]:
img_gray_naive = img_t.mean(-3)
batch_gray_naive = batch_t.mean(-3)
img_gray_naive.shape,batch_gray_naive.shape

(torch.Size([5, 5]), torch.Size([2, 5, 5]))

In [111]:
unsqueezed_weights = weights.unsqueeze(-1).unsqueeze_(-1) # adds 2 new dimensions , from [1] to [3,1,1]
img_weights = (img_t*unsqueezed_weights) #multiplies [3,5,5]*[3,1,1] and produces [3,5,5]
batch_weights = batch_t*unsqueezed_weights #multiplies [2,3,5,5]*[3,1,1] and produces [2,3,5,5]
img_gray_weighted = img_weights.sum(-3) #produces [5,5] from [3,5,5] input
batch_gray_weighted = batch_weights.sum(-3) #produces [2,5,5] from [2,3,5,5] input
batch_weights.shape,batch_t.shape,unsqueezed_weights.shape

(torch.Size([2, 3, 5, 5]), torch.Size([2, 3, 5, 5]), torch.Size([3, 1, 1]))

In [135]:
weights_named = torch.tensor([0.2126,0.7152,0.0722],names =['channels']) #named tensor
weights_named.shape

torch.Size([3])

In [138]:
img_named = img_t.refine_names('channels','rows','columns')
batch_named = batch_t.refine_names(...,'channels','rows','columns')
print(img_named.shape , img_named.names)
print(batch_named.shape , batch_named.names)

torch.Size([3, 5, 5]) ('channels', 'rows', 'columns')
torch.Size([2, 3, 5, 5]) (None, 'channels', 'rows', 'columns')


In [146]:
weights_aligned = weights_named.align_as(img_named)
print(weights_named.names , img_named.names)
print(weights_named.shape,img_named.shape)
print(weights_aligned.shape,weights_aligned.names)


('channels',) ('channels', 'rows', 'columns')
torch.Size([3]) torch.Size([3, 5, 5])
torch.Size([3, 1, 1]) ('channels', 'rows', 'columns')
