In [41]:
import numpy as np
import torch
import random

In [42]:
A=[]
for i in range(10):
    A.append(random.randint(1,100))
A

[74, 56, 42, 99, 33, 91, 63, 9, 58, 98]

In [43]:
a = torch.ones(3)

In [44]:
a

tensor([1., 1., 1.])

In [45]:
a[1]

tensor(1.)

In [46]:
a[0]

tensor(1.)

In [47]:
float(a[0])

1.0

In [48]:
a[2]=4
a

tensor([1., 1., 4.])

In [49]:
thistuple = ("apple", "banana", "cherry")
print(thistuple)

('apple', 'banana', 'cherry')


In [50]:
points = torch.zeros(6)
points[0]=4.0
points[1]=1.0
points[2]=5.0
points[3]=3.0
points[4]=2.0
points[5]=1

points


tensor([4., 1., 5., 3., 2., 1.])

In [51]:
x,y =float(points[0]),float(points[1])
x,y

(4.0, 1.0)

In [52]:
points = torch.tensor([[4,0],[5,3],[2,1]])
points[0][0]
for i in points :
    print(float(i[0]),float(i[1]))
print(points.size())

4.0 0.0
5.0 3.0
2.0 1.0
torch.Size([3, 2])


In [53]:
points.shape

torch.Size([3, 2])

In [54]:
P = torch.ones(3,2)
P
P.shape

torch.Size([3, 2])

In [55]:
torch.__version__

'2.5.0+cpu'

In [56]:
B= torch.tensor([1,2,3,4])
B

tensor([1, 2, 3, 4])

In [57]:
X = np.zeros(10)
X
Y=[0]*10
Y

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [58]:
some_list = list(range(10))
some_list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [59]:
some_list[:]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [60]:
some_list[1:4]

[1, 2, 3]

In [61]:
some_list[1:]

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [62]:
some_list[:4]

[0, 1, 2, 3]

In [63]:
some_list[:-1]

[0, 1, 2, 3, 4, 5, 6, 7, 8]

In [64]:
some_list[1:4:2]

[1, 3]

In [65]:
some_tensor = torch.tensor([[10,12],[10,12],[10,22],[10,12],[10,12],[10,22]])

In [66]:
some_tensor.shape

torch.Size([6, 2])

In [67]:
points = torch.tensor([[4,0],[5,3],[2,1]])
points

tensor([[4, 0],
        [5, 3],
        [2, 1]])

In [68]:
points[1:]

tensor([[5, 3],
        [2, 1]])

In [69]:
points[1:,0]

tensor([5, 2])

In [70]:
points[None]

tensor([[[4, 0],
         [5, 3],
         [2, 1]]])

In [71]:
img_t = torch.randn(3,5,5) #generates tensor of 3x5x5
img_t

tensor([[[ 1.0766e+00, -4.9914e-01, -7.6821e-01,  2.0973e+00,  1.4674e+00],
         [-1.6025e+00,  6.5375e-01,  3.2167e-01, -4.5941e-01,  2.8469e-01],
         [-1.2708e+00,  8.4926e-01,  7.3596e-01,  1.1179e-01, -2.7068e-01],
         [ 1.0049e+00, -1.4406e+00, -2.0396e+00,  2.9707e-01,  2.9055e-01],
         [ 5.9392e-01, -1.2555e+00, -1.7357e-01,  1.3433e-01,  1.8178e-01]],

        [[-1.3459e+00, -2.0203e+00,  5.8236e-01, -4.8874e-01, -2.0171e+00],
         [ 1.2205e+00,  1.4801e+00,  8.7364e-01, -4.8672e-02,  5.3382e-01],
         [ 1.8660e+00, -4.3996e-01, -6.3627e-02, -6.0739e-01,  6.2029e-01],
         [ 1.1775e+00,  1.9089e+00, -1.2872e+00, -1.1211e+00,  2.4302e-01],
         [-6.1446e-01,  1.6494e-01, -5.3680e-01,  1.8138e+00,  9.0412e-02]],

        [[-1.9049e-03,  1.4243e+00, -2.0499e-01,  2.0246e+00,  6.5103e-01],
         [-1.0864e+00, -4.8453e-01,  3.0381e-02, -1.2898e-01,  1.1453e+00],
         [-1.1178e-01, -3.0389e-01,  1.1607e+00,  2.1468e+00, -8.7789e-01],
        

In [72]:
weights = torch.tensor([0.2126,0.7152,0.0722])
batch_t = torch.randn(2,3,5,5)
img_t.shape,batch_t.shape

(torch.Size([3, 5, 5]), torch.Size([2, 3, 5, 5]))

In [73]:
img_gray_naive = img_t.mean(-3)
batch_gray_naive = batch_t.mean(-3)
img_gray_naive.shape,batch_gray_naive.shape

(torch.Size([5, 5]), torch.Size([2, 5, 5]))

In [74]:
unsqueezed_weights = weights.unsqueeze(-1).unsqueeze_(-1) # adds 2 new dimensions , from [1] to [3,1,1]
img_weights = (img_t*unsqueezed_weights) #multiplies [3,5,5]*[3,1,1] and produces [3,5,5]
batch_weights = batch_t*unsqueezed_weights #multiplies [2,3,5,5]*[3,1,1] and produces [2,3,5,5]
img_gray_weighted = img_weights.sum(-3) #produces [5,5] from [3,5,5] input
batch_gray_weighted = batch_weights.sum(-3) #produces [2,5,5] from [2,3,5,5] input
batch_weights.shape,batch_t.shape,unsqueezed_weights.shape

(torch.Size([2, 3, 5, 5]), torch.Size([2, 3, 5, 5]), torch.Size([3, 1, 1]))

In [75]:
weights_named = torch.tensor([0.2126,0.7152,0.0722],names =['channels']) #named tensor
weights_named.shape

torch.Size([3])

In [76]:
img_named = img_t.refine_names('channels','rows','columns')
batch_named = batch_t.refine_names(...,'channels','rows','columns')
print(img_named.shape , img_named.names)
print(batch_named.shape , batch_named.names)

torch.Size([3, 5, 5]) ('channels', 'rows', 'columns')
torch.Size([2, 3, 5, 5]) (None, 'channels', 'rows', 'columns')


In [77]:
weights_aligned = weights_named.align_as(img_named)
print(weights_named.names , img_named.names)
print(weights_named.shape,img_named.shape)
print(weights_aligned.shape,weights_aligned.names)


('channels',) ('channels', 'rows', 'columns')
torch.Size([3]) torch.Size([3, 5, 5])
torch.Size([3, 1, 1]) ('channels', 'rows', 'columns')
